# Generated by Django 5.1.4 on 2025-01-02 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hope', '0006_sponsor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sponsor',
            new_name='Client',
        ),
    ]
