# Generated by Django 5.1.4 on 2025-01-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hope', '0007_rename_sponsor_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(default='Hope', max_length=50),
        ),
    ]
