# Generated by Django 5.1.4 on 2025-02-11 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hope', '0012_bankaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('work', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to='board_members/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='program_images/')),
                ('description', models.TextField()),
                ('color', models.CharField(default='#cc1631', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='resource/')),
                ('color', models.CharField(default='#cc1631', max_length=7)),
            ],
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='facebook_username',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='instagram_username',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='twitter_url',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='twitter_username',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='self_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('color', models.CharField(default='#cc1631', max_length=7)),
                ('image', models.ImageField(upload_to='project_images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='project_videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='Hope.program')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('color', models.CharField(default='#cc1631', max_length=7)),
                ('image', models.ImageField(upload_to='resource_images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='resource_videos/')),
                ('link', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resourceDetails', to='Hope.resource')),
            ],
        ),
    ]
