# Generated by Django 5.1.2 on 2025-03-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hope', '0013_boardmember_program_resource_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='volunteer_images/'),
        ),
    ]
